---
title: "FAIR Data Practices for Qualitative Research in Transdisciplinarity"
subtitle: "Presenting our work at the STS NL 2026 conference"
description: |
  We are excited to announce that our abstract has been accepted for the STS NL 2026 conference. The FAIRqual project will be represented in the track 'How to Make Science Better'.
categories:
  - conference
  - presentation
author:
  - name: "Dr. Franziska Mohr"
    url: https://tdlab.usys.ethz.ch/team/person-detail.franziska-mohr.html
    affiliation: USYS Transdisciplinarity Lab ETH Zurich
    affiliation_url: https://tdlab.usys.ethz.ch/
    orcid_id: 0000-0002-8323-7032
date: today
draft: false
css: ../../../style/styles.css
citation:
  type: post
  container-title: FAIRqual Project Blog
  url: https://fairqual.org/blog/2026-02-05-sts-nl2026
---

We are excited to announce that our abstract has been accepted for the [STS NL 2026 conference](https://www.utwente.nl/en/bms/sts-nl2026/). The FAIRqual project will be represented in the track 'How to Make Science Better', where we will talk about how the use of FAIR qualitative data in Td research could contribute to this ambition. Are you planning to join STS NL 2026 as well? Get in touch!

## Abstract: FAIR Data Practices for Qualitative Research in Transdisciplinarity

In recent years, open research data (ORD) practices have gained traction, as evidenced by funding calls and journals establishing them as a requirement. ORD intends to 'make science better ' by increasing transparency and reproducibility, and by making datasets reusable and citable. However, ORD practises are often based on quantitative data cultures, and are rarely applied to qualitative data. Given their growing importance, it is important to rethink ORD practices for qualitative data, taking into account the practical, epistemological, and ethical challenges of sharing such data. This need comes to the fore when conducting transdisciplinary (Td) research, where new forms of engagement between science and society co-produce problem framings and project outputs. Sharing interview or workshop data from Td projects could allow for improved learning between Td processes and increase engagement between science and society.

In the FAIRqual project we address this issue by asking the questions: What are options to share this data according to FAIR principles? How to navigate the ethical issues of research participant protection and the benefits of sharing qualitative data? Who processes and stores data from Td research, and for whom? During a workshop with Td researchers, we identified key considerations and questions relating to open qualitative data in Td research. In a second step, we explored these in expert interviews with experienced Td researchers and open science experts. Based on our insights, our aim is to provide guidance on opening up qualitative data and encourage reflection on the current data management in Td research. By doing this, we do not view ORD as a measure of 'better science', but rather as a tool to start conversations about data documentation and data governance in Td projects. This has the potential to strengthen both research integrity and the partnership between science and society.

---

If you would like to get in touch or receive updates of the projects, [drop us a line](mailto:franziska.mohr@usys.ethz.ch?subject=FAIRqual request)!
